#ifndef VID2LED_CONFIG_H
#define VID2LED_CONFIG_H

#define VID2LEN_FRAME_COLS 16  /* width */
#define VID2LEN_FRAME_ROWS 16  /* height */

#define VID2LEN_USE_STATIC_BUFFER 0
#define VID2LEN_STATIC_BUFFER_LENGTH 32

#define VID2LEN_DEBUG_MESSAGES 1
#define VID2LEN_DEBUG_MSG_MAX_LENGTH 128

#define MAX_SOCK_MESSAGE_LEN 65514  /* must be divisible by 3 */

#endif // VID2LED_CONFIG_H
